### ISSUE TITLE
How to save the key in PPT/PEM format?

### ISSUE THREAD

**Issue by AndreFabris** [ssx/php-ssh-keypair#2]
Hi,

I am using your library to generate keys, however to log into the server I need Private key in PPT or PEM format. Any ideas how to save it as such?

thanks

ANdre

**Comment by ssx** [comment]
Hi @AndreFabris!

https://github.com/ssx/php-ssh-keypair/blob/e37ca2c750907bbdf8108a56b519afa7c6bf42be/src/KeyPair.php#L40

You'll need to update around that line with the format for PEM, the formats are listed in this underlaying phpseclib:

https://github.com/phpseclib/phpseclib/tree/master/phpseclib/Crypt
